extends: stylelint-config-standard
customSyntax: postcss-scss
plugins:
  - "@stylistic/stylelint-plugin"
  - stylelint-order
  - stylelint-scss
rules:
  "@stylistic/block-opening-brace-space-before": "always"
  "@stylistic/indentation": 2
  "@stylistic/max-line-length": null
  "@stylistic/no-eol-whitespace": true
  "@stylistic/no-missing-end-of-source-newline": true
  "@stylistic/number-leading-zero": never
  "@stylistic/string-quotes": null
  "@stylistic/value-list-max-empty-lines": 1
  annotation-no-unknown: null # Interfere with Sass !global !default
  at-rule-empty-line-before:
    - always
    - except:
        - blockless-after-same-name-blockless
        - inside-block
        - first-nested
      ignore:
        - after-comment
        - inside-block
  at-rule-no-unknown: null # Prefer scss/at-rule-no-unknown
  declaration-empty-line-before:
    - never
    - ignore:
        - after-comment
  font-family-name-quotes: always-where-recommended
  font-family-no-missing-generic-family-keyword: null
  function-no-unknown: null # Interfere with Sass functions
  function-url-quotes: never
  import-notation: null # Interfere with Sass imports
  media-query-no-invalid: null #Interfere with media queries using Sass variables
  no-descending-specificity: null
  selector-attribute-quotes: always
  selector-type-no-unknown:
    - true
    - ignore:
        - custom-elements
  #  string-quotes: double ## TODO
  order/order:
    - custom-properties
    - dollar-variables
    - declarations
    - type: at-rule
      name: include
      parameter: breakpoint
      hasBlock: true
    - type: at-rule
      name: media
      hasBlock: true
    - rules
  order/properties-alphabetical-order: true
  scss/at-mixin-argumentless-call-parentheses: always
  scss/at-rule-no-unknown: true
  scss/dollar-variable-empty-line-before:
    - always
    - except:
        - first-nested
        - after-comment
        - after-dollar-variable
  scss/load-no-partial-leading-underscore: true
#  scss/selector-no-redundant-nesting-selector: true ## TODO
